### PR TITLE
Add input vector script for splitting compound cookies

### PR DESCRIPTION
**Pull request by jhowlett96**
Add a new input vector script that splits compound cookies and lets ZAP use these individual cookies values to target attacks.

### CODE REVIEW

**Comment by thc202** [comment]
Wrong repo?

**Comment by jhowlett96** [comment]
I was asked in [https://github.com/zaproxy/zaproxy/issues/6582](url) to generate PR in community scripts to add my custom script. This is my first PR and so do not know ZAP's file structure. If you know of a better place please let me know.

**Comment by thc202** [comment]
You created the pull request against your fork, instead of the main repository.

Regarding the location, the script needs to be placed in the `variant` directory.

**Comment by jhowlett96** [comment]
Thankyou for the guidance. I will sort it out now.

**Pull request closed without merging**
